export const UPDATE_USER_NAME = "UPDATE_USER_NAME";
export const UPDATE_USER_EMAIL = "UPDATE_USER_EMAIL";
export const UPDATE_USER_GENDER = "UPDATE_USER_GENDER";
export const UPDATE_USER_DOB = "UPDATE_USER_DOB";
export const UPDATE_USER_PHONE = "UPDATE_USER_PHONE";
export const PROFILE_ACCESS = "PROFILE_ACCESS";
export const DISPLAY_PROFILE = "DISPLAY_PROFILE";